
version: "3"

services:
    im-coturn:
        container_name: im-coturn
        image: coturn/coturn:4.6.2-alpine
        command: turnserver -v -a -c /etc/coturn/conf/coturn.conf
        restart: always
        ports:
            - PORT_COTURN_LISTEN_OS:3478
            - PORT_COTURN_LISTEN_OS:3478/udp
            - PORT_COTURN_LISTEN_TLS_OS:5349
            - PORT_COTURN_LISTEN_TLS_OS:5349/udp
            - PORT_COTURN_RELAY_BEGIN_OS-PORT_COTURN_RELAY_END_OS:PORT_COTURN_RELAY_BEGIN_OS-PORT_COTURN_RELAY_END_OS/udp
        # network_mode: "host"
        environment:
            - DETECT_EXTERNAL_IP=yes
            - DETECT_RELAY_IP=yes
        volumes:
            -  deploydir/docker_volumes_data/coturn/conf:/etc/coturn/conf
            -  deploydir/docker_volumes_data/coturn/certs:/etc/coturn/ssl
            -  deploydir/docker_volumes_data/coturn/log:/var/log/coturn/
networks:
  default:
    external:
      name: turn-network
